### ISSUE TITLE
refactor readNWISodbc

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#3]
This function is clunky and in need of a refactor. Take this OSW project as an opportunity to streamline.

**Comment by tjmills** [comment]
Not doing a major refactor because of time but will clean up a bit

**Comment by cpenn-usgs** [comment]
One of the NWIS checks (20.42 Medium Code conflicts with site type) requires site type information. Should this be built into the ODBC pull, use dataRetrieval tools, or ignored (not sure if NWIS already won't let you add medium codes to conflicting site types).

**Comment by tjmills** [comment]
OK, I am adding that to the nwisODBC output

**Comment by tmills-usgs** [comment]
testing slack integration
