### ISSUE TITLE
better testing site/example data for all checks

### ISSUE THREAD

**Issue by cpenn-usgs** [USGS-R/sedReview#47]
sediment sampling site w/ bag sampler, EWI, EDI used sometime in past
after new example data, will need to regenerate testthat data sets for each function

**Comment by cpenn-usgs** [comment]
testData complete
exampleData for package (trimmed testData) still needed. Roxygen header will need to be modified for each function to load new exampleData (most currently loading testData)

**Comment by tjmills** [comment]
This is now done
