### ISSUE TITLE
Non-unique RECORD_NO bombing functions

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#53]
When pulling data from multiple states the situation can arrise where there are non-unique record numbers.

The most obvious way to deal with this is to key off of both the SITE_NO and RECORD_NO

@cpenn-usgs If this affects a bunch of your functions I will include a new variable called UID that is a paste of the SITE_NO and RECORD_NO.

**Comment by tjmills** [comment]
@cpenn-usgs Can you check your functions and post issue you find in this thread

**Comment by cpenn-usgs** [comment]
@tmills-usgs yeah this will bomb all my functions. I can modify them to do SITE_NO and RECORD_NO unless you are going to make a combined ID

**Comment by tjmills** [comment]
good. Whole-sale bomb of the entire package. nice.

OK, I will make a new UID variable and we will key off of that

**Comment by tjmills** [comment]
See, unforseen issues when you start hitting multiple databases

:neckbeard:
