### ISSUE TITLE
Reshape table output from sedOutliers

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#6]
I think the table would be better formatted where the quantiles are the columns, and each row corresponds to the data type (i.e. SSL, etc)

**Comment by cpenn-usgs** [comment]
with the modified workplan, this function was modified to take user supplied threshold values (ex. 0.1, 0.9) and output a list of flagged samples based on those thresholds. A table of quantiles/values is no longer output, a user would have to generate this (or percentiles, boxplot, etc.) first to input thresholds they determine.
