### ISSUE TITLE
remove duplicate entries from all flag tables

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#65]
There are duplicate UIDs because in the long datatable some results are duplicated because of different sample or result comments, but hte result is the same. So ```unique(exampleData) == exampleData``` but ```unique(hasQFlags ) != hasQFlags```

**Comment by cpenn-usgs** [comment]
I've tested each function so far with both returnAll = T & F, and don't see any instances where this occurs yet. In all the functions so far, the first step extracts the needed info then uses unique to remove duplicates, so none of the function outputs contain duplicate entries
