### ISSUE TITLE
Add option to get_localNWIS to pull from a user specified QAQC database

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#69]

**Comment by cpenn-usgs** [comment]
with the qa.db option uncommented in get_localNWIS I think this is now taken care of. The issue may arise if there are multiple QAQC databases. You could use get_localNWIS to pull from two QAQC databases and not pull any environmental samples. Might be better to call them DB1, DB2...DBn in a future version of get_localNWIS and re-open this issue.
