### ISSUE TITLE
bug in check_all

### ISSUE THREAD

**Issue by tjmills** [USGS-R/sedReview#70]
check_all fails when filtering on Qflags==T, removed that filter for now to merge PR but needs to be addressed

**Comment by tjmills** [comment]
ok, so that didnt fix it. There is some bug with dplyr::filter that is bombing it in the example

I am merging for now so  I can close my fork

**Comment by cpenn-usgs** [comment]
Might have been a base::filter vs. dplyr::filter issue. Added dplyr::filter syntax and added to Roxygen header and re-organized text for better code reading. Seems to work now.
